#!/usr/bin/env bash
# takes 4 arguments and transfers a file from our client to a serve
# Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY

if [ $# -ge 4 ]
then
	scp -o "StrictHostKeyChecking=no" -i "$4" "$1" "$3@$2":~/
else
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
