#!/usr/bin/env bash
# Installs nginx on my server
# Nginx must return a page with "Hello world" if querying at its root

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html
sudo service nginx start
