#!/usr/bin/env bash
# Configures Nginx server so that /redirect_me is redirecting to another page
# redirection must be a “301 Moved Permanently”

ADD301_REDIRECT="\\\tlocation /redirect_me {\n\t\t return 301 https://google.com;\n\t}\n"

sudo apt-get -y update
sudo apt-get -y install nginx

echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html
# add at line 30
sudo sed -i "30i $ADD301_REDIRECT" /etc/nginx/sites-available/default 
sudo service nginx start
