#!/usr/bin/env bash
#script that manages manage_my_process

pid_file="/var/run/my_process.pid"

start_process()
{
	./manage_my_process &
	pgrep -f ./manage_my_process > "$pid_file"
}

stop_process()
{
	kill "$(cat $pid_file)"
	rm "$pid_file"
}

if [ $# == 1 ] && { [ "$1" == 'start' ] || [ "$1" == 'stop' ] || [ "$1" == 'restart' ]; }
then
	case $1 in
		"start")
			start_process
			echo "manage_my_process started"
			;;
		"stop")
			stop_process
			echo "manage_my_process stopped"
			;;
		"restart")
			stop_process
			start_process
			echo "manage_my_process restarted"
			;;
	esac
else
	echo "Usage: manage_my_process {start|stop|restart}"
fi

exit 0
