#!/usr/bin/env bash
#script that displays To infinity and beyond indefinitely
#displays I am invincible!!! when receiving a SIGTERM
while true
do
	echo "To infinity and beyond"
	sleep 2
	trap "I am invincible!!!" SIGTERM
done
