#!/usr/bin/env bash
#script that displays To infinity and beyond indefinitely
#displays I am invincible!!! when receiving a SIGTERM
output()
{
	echo "I am invincible!!!"
}
while true
do
	echo "To infinity and beyond"
	sleep 2
	trap output SIGTERM
done
