#!/usr/bin/env bash
#This script is displaying "Best School" 10 times using for loop
for _ in {0..9} ; do echo "Best School" ; done
# _ is a dummy variable it is used when it is not called inside of the loop
