#!/usr/bin/env bash
#script that displays numbers from 1 to 100
#with Fizz for multiple of 3, Buzz for multiple of 5
#and FizzBuzz for multiple of 3 and 5
i=1
while [ $i -le 100 ]
do
	if [ $((i % 3)) == 0 ] && [ $((i % 5)) == 0 ]
	then
		echo "FizzBuzz"
	elif [ $((i % 3)) == 0 ]
	then
		echo "Fizz"
	elif [ $((i % 5)) == 0 ]
	then
		echo "Buzz"
	else
		echo $i
	fi
	((i++))
done
