#!/usr/bin/env bash
#script that displays the content of the file /etc/passwd
#only display username, user_id, home_directory_path
file="/etc/passwd"
while read line
do
	echo "$line" | cut -d ":" -f 1,3,6
done < $file
