#!/usr/bin/env bash
#This script is displaying "Best School" 10 times using until loop
i=0
until [ $i == 9 ]
do
	echo "Best School"
	i=$((i + 1))
done
#one line version
#i=0; until [ $i -le 9 ]; do echo "Best School" $((i++)); done
