#!/usr/bin/env bash
#This script is displaying "Best School" 10 times
#with "Hi" before last print using while loop
i=0
while [ $i -le 9 ]
do
	echo "Best School"
	if [ $i == 8 ]
	then
		echo "Hi"
	fi
	i=$((i + 1))
done
#one line version
#i=0; while [ $i -le 9 ]; do echo "Best School" $((i++)); done
