#!/usr/bin/env bash
#This script is displaying "Best School" 10 times
#except for 4th and 8th iteration
i=1
while [ $i -le 10 ]
do
	if [ $i == 8 ]
	then
		echo "good luck"
	elif [ $i == 4 ]
	then
		echo "bad luck"
	else
		echo "Best School"
	fi
	i=$((i + 1))
done
