#!/usr/bin/env bash
#This script displays times
#Hours form 0 to 12 and minutes from 1 to 59
hour=0
min=1
while [ $hour -le 12 ]
do
	echo "Hour: $hour"
	while [ $min -le 59 ]
	do
		echo $min
		((min++))
	done
	min=1
	((hour++))
done
